name: 'GPT PR Reviewer'
description: 'Review PR and suggest comments, improvments, using ChatGPT'
author: 'Galadrim'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

runs:
  using: node20
  main: dist/index.js
